# Generated by Django 6.0.4 on 2026-05-21 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_delete_game_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=200)),
                ('user_games', models.IntegerField(default=0)),
                ('user_wins', models.IntegerField(default=0)),
                ('user_losses', models.IntegerField(default=0)),
                ('user_saved_game', models.IntegerField(default=0)),
                ('user_current_games', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('game_board', models.CharField(max_length=200)),
                ('game_time', models.IntegerField(default=0)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.user')),
            ],
        ),
    ]
