# Generated by Django 6.0.4 on 2026-06-04 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0003_user_game'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='game_time',
            new_name='game_time_black',
        ),
        migrations.AddField(
            model_name='game',
            name='game_time_white',
            field=models.IntegerField(default=0),
        ),
    ]
