# Generated by Django 6.0.4 on 2026-06-08 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0004_rename_game_time_game_game_time_black_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_password',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
