DROP TABLE country;

CREATE TABLE `countries`.`country` (
  `country_id` INT NOT NULL AUTO_INCREMENT,
  `country_name` VARCHAR(100) NOT NULL,
  `country_abbreviation` VARCHAR(10) NULL,
  `country_continent` VARCHAR(45) NOT NULL,
  `country_flag` VARCHAR(1000) NULL,
  `country_capital` VARCHAR(45) NULL,
  `country_leader` VARCHAR(45) NULL,
  `country_independence_year` INT NULL,
  `country_area` INT NULL,
  `country_population` INT NULL,
  PRIMARY KEY (`country_id`));

-- Example
-- INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('United States of America', 'US', 'North America', NULL, 'Washington D.C.', 'President Donald Trump', 1776, 3796742, 331449281);

-- Test data set
-- INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES
-- ('United States', 'USA', 'North America', NULL, 'Washington, D.C.', 'Joe Biden', 1776, 9833520, 331000000),
-- ('Canada', 'CAN', 'North America', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Canada_%28Pantone%29.svg/1920px-Flag_of_Canada_%28Pantone%29.svg.png', 'Ottawa', 'Justin Trudeau', 1867, 9984670, 38000000),
-- ('United Kingdom', 'UK', 'Europe', NULL, 'London', 'Rishi Sunak', 1707, 243610, 67000000),
-- ('Australia', 'AUS', 'Oceania', 'https://upload.wikimedia.org/wikipedia/commons/8/88/Flag_of_Australia_%28converted%29.svg', 'Canberra', 'Anthony Albanese', 1901, 7692024, 26000000),
-- ('India', 'IND', 'Asia', NULL, 'New Delhi', 'Narendra Modi', 1947, 3287263, 1400000000),
-- ('Brazil', 'BRA', 'South America', NULL, 'Brasília', 'Luiz Inácio Lula da Silva', 1822, 8515767, 214000000),
-- ('Germany', 'DEU', 'Europe', NULL, 'Berlin', 'Olaf Scholz', 1871, 357022, 83000000),
-- ('Japan', 'JPN', 'Asia', NULL, 'Tokyo', 'Fumio Kishida', 660, 377975, 125000000),
-- ('South Africa', 'ZAF', 'Africa', NULL, 'Pretoria', 'Cyril Ramaphosa', 1910, 1221037, 60000000),
-- ('France', 'FRA', 'Europe', NULL, 'Paris', 'Emmanuel Macron', 843, 551695, 67000000);

-- Complete data set
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Afghanistan','AF','Asia','https://upload.wikimedia.org/wikipedia/commons/9/9a/Flag_of_Afghanistan.svg','Kabul','Hibatullah Akhundzada',1919,652230,41100000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Albania','AL','Europe','https://upload.wikimedia.org/wikipedia/commons/3/36/Flag_of_Albania.svg','Tirana','Bajram Begaj',1912,28748,2800000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Algeria','DZ','Africa','https://upload.wikimedia.org/wikipedia/commons/7/77/Flag_of_Algeria.svg','Algiers','Abdelmadjid Tebboune',1962,2381741,44900000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Andorra','AD','Europe','https://upload.wikimedia.org/wikipedia/commons/1/19/Flag_of_Andorra.svg','Andorra la Vella','Joan-Enric Vives',1278,468,80000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Angola','AO','Africa','https://upload.wikimedia.org/wikipedia/commons/9/9d/Flag_of_Angola.svg','Luanda','João Lourenço',1975,1246700,35600000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Argentina','AR','South America','https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_Argentina.svg','Buenos Aires','Javier Milei',1816,2780400,46000000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Armenia','AM','Asia','https://upload.wikimedia.org/wikipedia/commons/2/2f/Flag_of_Armenia.svg','Yerevan','Vahagn Khachaturyan',1991,29743,2800000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Australia','AU','Oceania','https://upload.wikimedia.org/wikipedia/commons/b/b9/Flag_of_Australia.svg','Canberra','Anthony Albanese',1901,7692024,26000000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Austria','AT','Europe','https://upload.wikimedia.org/wikipedia/commons/4/41/Flag_of_Austria.svg','Vienna','Alexander Van der Bellen',1955,83879,9000000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Azerbaijan','AZ','Asia','https://upload.wikimedia.org/wikipedia/commons/d/dd/Flag_of_Azerbaijan.svg','Baku','Ilham Aliyev',1991,86600,10300000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Bahamas','BS','North America','https://upload.wikimedia.org/wikipedia/commons/9/93/Flag_of_the_Bahamas.svg','Nassau','Philip Davis',1973,13943,400000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Bahrain','BH','Asia','https://upload.wikimedia.org/wikipedia/commons/2/2c/Flag_of_Bahrain.svg','Manama','Hamad bin Isa Al Khalifa',1971,765,1500000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Bangladesh','BD','Asia','https://upload.wikimedia.org/wikipedia/commons/f/f9/Flag_of_Bangladesh.svg','Dhaka','Sheikh Hasina',1971,147570,171000000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Barbados','BB','North America','https://upload.wikimedia.org/wikipedia/commons/e/ef/Flag_of_Barbados.svg','Bridgetown','Sandra Mason',1966,430,280000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Belarus','BY','Europe','https://upload.wikimedia.org/wikipedia/commons/8/85/Flag_of_Belarus.svg','Minsk','Alexander Lukashenko',1991,207600,9300000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Belgium','BE','Europe','https://upload.wikimedia.org/wikipedia/commons/6/65/Flag_of_Belgium.svg','Brussels','Philippe',1830,30528,11700000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Belize','BZ','North America','https://upload.wikimedia.org/wikipedia/commons/e/e7/Flag_of_Belize.svg','Belmopan','Johnny Briceño',1981,22966,420000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Benin','BJ','Africa','https://upload.wikimedia.org/wikipedia/commons/0/0a/Flag_of_Benin.svg','Porto-Novo','Patrice Talon',1960,114763,13300000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Bhutan','BT','Asia','https://upload.wikimedia.org/wikipedia/commons/9/91/Flag_of_Bhutan.svg','Thimphu','Jigme Khesar Namgyel Wangchuck',1907,38394,800000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Bolivia','BO','South America','https://upload.wikimedia.org/wikipedia/commons/4/48/Flag_of_Bolivia.svg','Sucre','Luis Arce',1825,1098581,12000000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Bosnia and Herzegovina','BA','Europe','https://upload.wikimedia.org/wikipedia/commons/b/bf/Flag_of_Bosnia_and_Herzegovina.svg','Sarajevo','Željka Cvijanović',1992,51209,3200000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Botswana','BW','Africa','https://upload.wikimedia.org/wikipedia/commons/f/fa/Flag_of_Botswana.svg','Gaborone','Mokgweetsi Masisi',1966,581730,2600000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Brazil','BR','South America','https://upload.wikimedia.org/wikipedia/en/0/05/Flag_of_Brazil.svg','Brasilia','Luiz Inácio Lula da Silva',1822,8515767,214000000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Brunei','BN','Asia','https://upload.wikimedia.org/wikipedia/commons/9/9c/Flag_of_Brunei.svg','Bandar Seri Begawan','Hassanal Bolkiah',1984,5765,450000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Bulgaria','BG','Europe','https://upload.wikimedia.org/wikipedia/commons/9/9a/Flag_of_Bulgaria.svg','Sofia','Rumen Radev',1908,110879,6900000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Burkina Faso','BF','Africa','https://upload.wikimedia.org/wikipedia/commons/3/31/Flag_of_Burkina_Faso.svg','Ouagadougou','Ibrahim Traoré',1960,274223,23000000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Burundi','BI','Africa','https://upload.wikimedia.org/wikipedia/commons/5/50/Flag_of_Burundi.svg','Gitega','Évariste Ndayishimiye',1962,27834,13000000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Cabo Verde','CV','Africa','https://upload.wikimedia.org/wikipedia/commons/3/38/Flag_of_Cape_Verde.svg','Praia','José Maria Neves',1975,4033,600000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Cambodia','KH','Asia','https://upload.wikimedia.org/wikipedia/commons/8/83/Flag_of_Cambodia.svg','Phnom Penh','Hun Manet',1953,181035,17000000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Cameroon','CM','Africa','https://upload.wikimedia.org/wikipedia/commons/4/4f/Flag_of_Cameroon.svg','Yaoundé','Paul Biya',1960,475442,28000000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Canada','CA','North America','https://upload.wikimedia.org/wikipedia/commons/c/cf/Flag_of_Canada.svg','Ottawa','Justin Trudeau',1867,9984670,40000000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Central African Republic','CF','Africa','https://upload.wikimedia.org/wikipedia/commons/6/6f/Flag_of_the_Central_African_Republic.svg','Bangui','Faustin-Archange Touadéra',1960,622984,5500000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Chad','TD','Africa','https://upload.wikimedia.org/wikipedia/commons/4/4b/Flag_of_Chad.svg','N''Djamena','Mahamat Déby',1960,1284000,18000000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Chile','CL','South America','https://upload.wikimedia.org/wikipedia/commons/7/78/Flag_of_Chile.svg','Santiago','Gabriel Boric',1818,756102,19500000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('China','CN','Asia','https://upload.wikimedia.org/wikipedia/commons/f/fa/Flag_of_the_People%27s_Republic_of_China.svg','Beijing','Xi Jinping',1949,9596961,1410000000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Colombia','CO','South America','https://upload.wikimedia.org/wikipedia/commons/2/21/Flag_of_Colombia.svg','Bogotá','Gustavo Petro',1810,1141748,52000000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Comoros','KM','Africa','https://upload.wikimedia.org/wikipedia/commons/9/94/Flag_of_the_Comoros.svg','Moroni','Azali Assoumani',1975,2235,900000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Democratic Republic of the Congo','CD','Africa','https://upload.wikimedia.org/wikipedia/commons/6/6f/Flag_of_the_Democratic_Republic_of_the_Congo.svg','Kinshasa','Félix Tshisekedi',1960,2344858,102000000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Republic of the Congo','CG','Africa','https://upload.wikimedia.org/wikipedia/commons/9/92/Flag_of_the_Republic_of_the_Congo.svg','Brazzaville','Denis Sassou Nguesso',1960,342000,6000000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Costa Rica','CR','North America','https://upload.wikimedia.org/wikipedia/commons/f/f2/Flag_of_Costa_Rica.svg','San José','Rodrigo Chaves Robles',1821,51100,5200000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Croatia','HR','Europe','https://upload.wikimedia.org/wikipedia/commons/1/1b/Flag_of_Croatia.svg','Zagreb','Zoran Milanović',1991,56594,3900000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Cuba','CU','North America','https://upload.wikimedia.org/wikipedia/commons/b/bd/Flag_of_Cuba.svg','Havana','Miguel Díaz-Canel',1902,109884,11000000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Cyprus','CY','Europe','https://upload.wikimedia.org/wikipedia/commons/d/d4/Flag_of_Cyprus.svg','Nicosia','Nikos Christodoulides',1960,9251,1200000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Czechia','CZ','Europe','https://upload.wikimedia.org/wikipedia/commons/c/cb/Flag_of_the_Czech_Republic.svg','Prague','Petr Pavel',1993,78865,10700000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Denmark','DK','Europe','https://upload.wikimedia.org/wikipedia/commons/9/9c/Flag_of_Denmark.svg','Copenhagen','Frederik X',1849,42933,5900000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Djibouti','DJ','Africa','https://upload.wikimedia.org/wikipedia/commons/3/34/Flag_of_Djibouti.svg','Djibouti','Ismaïl Omar Guelleh',1977,23200,1100000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Dominica','DM','North America','https://upload.wikimedia.org/wikipedia/commons/c/c4/Flag_of_Dominica.svg','Roseau','Sylvanie Burton',1978,751,72000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Dominican Republic','DO','North America','https://upload.wikimedia.org/wikipedia/commons/9/9f/Flag_of_the_Dominican_Republic.svg','Santo Domingo','Luis Abinader',1844,48671,11300000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Ecuador','EC','South America','https://upload.wikimedia.org/wikipedia/commons/e/e8/Flag_of_Ecuador.svg','Quito','Daniel Noboa',1822,283561,18000000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Egypt','EG','Africa','https://upload.wikimedia.org/wikipedia/commons/f/fe/Flag_of_Egypt.svg','Cairo','Abdel Fattah el-Sisi',1922,1002450,111000000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('El Salvador','SV','North America','https://upload.wikimedia.org/wikipedia/commons/3/34/Flag_of_El_Salvador.svg','San Salvador','Nayib Bukele',1821,21041,6400000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Equatorial Guinea','GQ','Africa','https://upload.wikimedia.org/wikipedia/commons/3/31/Flag_of_Equatorial_Guinea.svg','Malabo','Teodoro Obiang Nguema Mbasogo',1968,28051,1700000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Eritrea','ER','Africa','https://upload.wikimedia.org/wikipedia/commons/2/29/Flag_of_Eritrea.svg','Asmara','Isaias Afwerki',1993,117600,3600000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Estonia','EE','Europe','https://upload.wikimedia.org/wikipedia/commons/8/8f/Flag_of_Estonia.svg','Tallinn','Alar Karis',1918,45227,1300000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Eswatini','SZ','Africa','https://upload.wikimedia.org/wikipedia/commons/f/fb/Flag_of_Eswatini.svg','Mbabane','Mswati III',1968,17364,1200000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Ethiopia','ET','Africa','https://upload.wikimedia.org/wikipedia/commons/7/71/Flag_of_Ethiopia.svg','Addis Ababa','Sahle-Work Zewde',1941,1104300,123000000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Fiji','FJ','Oceania','https://upload.wikimedia.org/wikipedia/commons/b/ba/Flag_of_Fiji.svg','Suva','Wiliame Katonivere',1970,18274,930000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Finland','FI','Europe','https://upload.wikimedia.org/wikipedia/commons/b/bc/Flag_of_Finland.svg','Helsinki','Alexander Stubb',1917,338455,5500000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('France','FR','Europe','https://upload.wikimedia.org/wikipedia/en/c/c3/Flag_of_France.svg','Paris','Emmanuel Macron',1792,551695,65000000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Gabon','GA','Africa','https://upload.wikimedia.org/wikipedia/commons/0/04/Flag_of_Gabon.svg','Libreville','Brice Oligui Nguema',1960,267668,2400000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Gambia','GM','Africa','https://upload.wikimedia.org/wikipedia/commons/7/77/Flag_of_The_Gambia.svg','Banjul','Adama Barrow',1965,11295,2700000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Georgia','GE','Asia','https://upload.wikimedia.org/wikipedia/commons/0/0f/Flag_of_Georgia.svg','Tbilisi','Salome Zourabichvili',1991,69700,3700000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Germany','DE','Europe','https://upload.wikimedia.org/wikipedia/en/b/ba/Flag_of_Germany.svg','Berlin','Frank-Walter Steinmeier',1871,357022,83000000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Ghana','GH','Africa','https://upload.wikimedia.org/wikipedia/commons/1/19/Flag_of_Ghana.svg','Accra','Nana Akufo-Addo',1957,238535,34000000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Greece','GR','Europe','https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_Greece.svg','Athens','Katerina Sakellaropoulou',1821,131957,10400000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Grenada','GD','North America','https://upload.wikimedia.org/wikipedia/commons/b/bc/Flag_of_Grenada.svg','St. George''s','Dickon Mitchell',1974,344,125000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Guatemala','GT','North America','https://upload.wikimedia.org/wikipedia/commons/e/ec/Flag_of_Guatemala.svg','Guatemala City','Bernardo Arévalo',1821,108889,18000000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Guinea','GN','Africa','https://upload.wikimedia.org/wikipedia/commons/e/ed/Flag_of_Guinea.svg','Conakry','Mamady Doumbouya',1958,245857,14000000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Guinea-Bissau','GW','Africa','https://upload.wikimedia.org/wikipedia/commons/0/01/Flag_of_Guinea-Bissau.svg','Bissau','Umaro Sissoco Embaló',1973,36125,2100000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Guyana','GY','South America','https://upload.wikimedia.org/wikipedia/commons/9/99/Flag_of_Guyana.svg','Georgetown','Irfaan Ali',1966,214969,800000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Haiti','HT','North America','https://upload.wikimedia.org/wikipedia/commons/5/56/Flag_of_Haiti.svg','Port-au-Prince','Ariel Henry',1804,27750,11500000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Honduras','HN','North America','https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Flag_of_Honduras_%281949%E2%80%932022%2C_2026%E2%80%93present%29.svg/1920px-Flag_of_Honduras_%281949%E2%80%932022%2C_2026%E2%80%93present%29.svg.png','Tegucigalpa','Xiomara Castro',1821,112492,10500000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Hungary','HU','Europe','https://upload.wikimedia.org/wikipedia/commons/c/c1/Flag_of_Hungary.svg','Budapest','Tamás Sulyok',1918,93030,9700000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Iceland','IS','Europe','https://upload.wikimedia.org/wikipedia/commons/c/ce/Flag_of_Iceland.svg','Reykjavík','Halla Tómasdóttir',1944,103000,390000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('India','IN','Asia','https://upload.wikimedia.org/wikipedia/en/4/41/Flag_of_India.svg','New Delhi','Droupadi Murmu',1947,3287263,1428000000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Indonesia','ID','Asia','https://upload.wikimedia.org/wikipedia/commons/9/9f/Flag_of_Indonesia.svg','Jakarta','Joko Widodo',1945,1904569,277000000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Iran','IR','Asia','https://upload.wikimedia.org/wikipedia/commons/c/ca/Flag_of_Iran.svg','Tehran','Ali Khamenei',1979,1648195,89000000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Iraq','IQ','Asia','https://upload.wikimedia.org/wikipedia/commons/f/f6/Flag_of_Iraq.svg','Baghdad','Abdul Latif Rashid',1932,438317,45000000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Ireland','IE','Europe','https://upload.wikimedia.org/wikipedia/commons/4/45/Flag_of_Ireland.svg','Dublin','Michael D. Higgins',1922,70273,5300000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Israel','IL','Asia','https://upload.wikimedia.org/wikipedia/commons/d/d4/Flag_of_Israel.svg','Jerusalem','Isaac Herzog',1948,22072,9800000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Italy','IT','Europe','https://upload.wikimedia.org/wikipedia/en/0/03/Flag_of_Italy.svg','Rome','Sergio Mattarella',1861,301340,59000000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Jamaica','JM','North America','https://upload.wikimedia.org/wikipedia/commons/0/0a/Flag_of_Jamaica.svg','Kingston','Andrew Holness',1962,10991,2800000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Japan','JP','Asia','https://upload.wikimedia.org/wikipedia/en/9/9e/Flag_of_Japan.svg','Tokyo','Naruhito',660,377975,125000000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Jordan','JO','Asia','https://upload.wikimedia.org/wikipedia/commons/c/c0/Flag_of_Jordan.svg','Amman','Abdullah II',1946,89342,11200000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Kazakhstan','KZ','Asia','https://upload.wikimedia.org/wikipedia/commons/d/d3/Flag_of_Kazakhstan.svg','Astana','Kassym-Jomart Tokayev',1991,2724900,20000000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Kenya','KE','Africa','https://upload.wikimedia.org/wikipedia/commons/4/49/Flag_of_Kenya.svg','Nairobi','William Ruto',1963,580367,54000000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Kiribati','KI','Oceania','https://upload.wikimedia.org/wikipedia/commons/d/d3/Flag_of_Kiribati.svg','Tarawa','Taneti Maamau',1979,811,130000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Kuwait','KW','Asia','https://upload.wikimedia.org/wikipedia/commons/a/aa/Flag_of_Kuwait.svg','Kuwait City','Mishal Al-Ahmad Al-Jaber Al-Sabah',1961,17818,4300000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Kyrgyzstan','KG','Asia','https://upload.wikimedia.org/wikipedia/commons/c/c7/Flag_of_Kyrgyzstan.svg','Bishkek','Sadyr Japarov',1991,199951,7000000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Laos','LA','Asia','https://upload.wikimedia.org/wikipedia/commons/5/56/Flag_of_Laos.svg','Vientiane','Thongloun Sisoulith',1953,236800,7500000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Latvia','LV','Europe','https://upload.wikimedia.org/wikipedia/commons/8/84/Flag_of_Latvia.svg','Riga','Edgars Rinkēvičs',1918,64589,1900000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Lebanon','LB','Asia','https://upload.wikimedia.org/wikipedia/commons/5/59/Flag_of_Lebanon.svg','Beirut','Joseph Aoun',1943,10452,5500000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Lesotho','LS','Africa','https://upload.wikimedia.org/wikipedia/commons/4/4a/Flag_of_Lesotho.svg','Maseru','Letsie III',1966,30355,2300000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Liberia','LR','Africa','https://upload.wikimedia.org/wikipedia/commons/b/b8/Flag_of_Liberia.svg','Monrovia','Joseph Boakai',1847,111369,5400000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Libya','LY','Africa','https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Libya.svg','Tripoli','Mohamed al-Menfi',1951,1759540,7000000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Liechtenstein','LI','Europe','https://upload.wikimedia.org/wikipedia/commons/4/47/Flag_of_Liechtenstein.svg','Vaduz','Hans-Adam II',1806,160,39000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Lithuania','LT','Europe','https://upload.wikimedia.org/wikipedia/commons/1/11/Flag_of_Lithuania.svg','Vilnius','Gitanas Nausėda',1918,65300,2800000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Luxembourg','LU','Europe','https://upload.wikimedia.org/wikipedia/commons/d/da/Flag_of_Luxembourg.svg','Luxembourg','Henri',1890,2586,670000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Madagascar','MG','Africa','https://upload.wikimedia.org/wikipedia/commons/b/bc/Flag_of_Madagascar.svg','Antananarivo','Andry Rajoelina',1960,587041,30000000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Malawi','MW','Africa','https://upload.wikimedia.org/wikipedia/commons/d/d1/Flag_of_Malawi.svg','Lilongwe','Lazarus Chakwera',1964,118484,21000000);
INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Malaysia','MY','Asia','https://upload.wikimedia.org/wikipedia/commons/6/66/Flag_of_Malaysia.svg','Kuala Lumpur','Ibrahim Iskandar',1957,330803,34000000);

INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Maldives','MV','Asia','https://upload.wikimedia.org/wikipedia/commons/0/0f/Flag_of_Maldives.svg','Malé','Mohamed Muizzu',1965,298,520000);

INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Mali','ML','Africa','https://upload.wikimedia.org/wikipedia/commons/9/92/Flag_of_Mali.svg','Bamako','Assimi Goïta',1960,1240192,22000000);

INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Malta','MT','Europe','https://upload.wikimedia.org/wikipedia/commons/7/73/Flag_of_Malta.svg','Valletta','Myriam Spiteri Debono',1964,316,540000);

INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Marshall Islands','MH','Oceania','https://upload.wikimedia.org/wikipedia/commons/2/2e/Flag_of_the_Marshall_Islands.svg','Majuro','Hilda Heine',1986,181,42000);

INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Mauritania','MR','Africa','https://upload.wikimedia.org/wikipedia/commons/4/43/Flag_of_Mauritania.svg','Nouakchott','Mohamed Ould Ghazouani',1960,1030700,4900000);

INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Mauritius','MU','Africa','https://upload.wikimedia.org/wikipedia/commons/7/77/Flag_of_Mauritius.svg','Port Louis','Prithvirajsing Roopun',1968,2040,1300000);

INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Mexico','MX','North America','https://upload.wikimedia.org/wikipedia/commons/f/fc/Flag_of_Mexico.svg','Mexico City','Claudia Sheinbaum',1810,1964375,129000000);

INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Micronesia','FM','Oceania','https://upload.wikimedia.org/wikipedia/commons/e/e4/Flag_of_the_Federated_States_of_Micronesia.svg','Palikir','Wesley Simina',1986,702,110000);

INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Moldova','MD','Europe','https://upload.wikimedia.org/wikipedia/commons/2/27/Flag_of_Moldova.svg','Chișinău','Maia Sandu',1991,33846,2500000);

INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Monaco','MC','Europe','https://upload.wikimedia.org/wikipedia/commons/e/ea/Flag_of_Monaco.svg','Monaco','Albert II',1297,2,39000);

INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Mongolia','MN','Asia','https://upload.wikimedia.org/wikipedia/commons/4/4c/Flag_of_Mongolia.svg','Ulaanbaatar','Ukhnaagiin Khürelsükh',1911,1564116,3400000);

INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Montenegro','ME','Europe','https://upload.wikimedia.org/wikipedia/commons/6/64/Flag_of_Montenegro.svg','Podgorica','Jakov Milatović',2006,13812,620000);

INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Morocco','MA','Africa','https://upload.wikimedia.org/wikipedia/commons/2/2c/Flag_of_Morocco.svg','Rabat','Mohammed VI',1956,446550,37000000);

INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Mozambique','MZ','Africa','https://upload.wikimedia.org/wikipedia/commons/d/d0/Flag_of_Mozambique.svg','Maputo','Filipe Nyusi',1975,801590,33000000);

INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Myanmar','MM','Asia','https://upload.wikimedia.org/wikipedia/commons/8/8c/Flag_of_Myanmar.svg','Naypyidaw','Min Aung Hlaing',1948,676578,55000000);

INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Namibia','NA','Africa','https://upload.wikimedia.org/wikipedia/commons/0/00/Flag_of_Namibia.svg','Windhoek','Nangolo Mbumba',1990,825615,2600000);

INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Nauru','NR','Oceania','https://upload.wikimedia.org/wikipedia/commons/3/30/Flag_of_Nauru.svg','Yaren','David Adeang',1968,21,12000);

INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Nepal','NP','Asia','https://upload.wikimedia.org/wikipedia/commons/9/9b/Flag_of_Nepal.svg','Kathmandu','Ram Chandra Poudel',1768,147516,30500000);

INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Netherlands','NL','Europe','https://upload.wikimedia.org/wikipedia/commons/2/20/Flag_of_the_Netherlands.svg','Amsterdam','Willem-Alexander',1581,41543,17800000);

INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('New Zealand','NZ','Oceania','https://upload.wikimedia.org/wikipedia/commons/3/3e/Flag_of_New_Zealand.svg','Wellington','Christopher Luxon',1907,268021,5200000);

INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Nicaragua','NI','North America','https://upload.wikimedia.org/wikipedia/commons/1/19/Flag_of_Nicaragua.svg','Managua','Daniel Ortega',1821,130373,6900000);

INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Niger','NE','Africa','https://upload.wikimedia.org/wikipedia/commons/f/f4/Flag_of_Niger.svg','Niamey','Abdourahamane Tchiani',1960,1267000,27000000);

INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Nigeria','NG','Africa','https://upload.wikimedia.org/wikipedia/commons/7/79/Flag_of_Nigeria.svg','Abuja','Bola Tinubu',1960,923768,223000000);

INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('North Korea','KP','Asia','https://upload.wikimedia.org/wikipedia/commons/5/51/Flag_of_North_Korea.svg','Pyongyang','Kim Jong Un',1948,120540,26000000);

INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('North Macedonia','MK','Europe','https://upload.wikimedia.org/wikipedia/commons/7/79/Flag_of_North_Macedonia.svg','Skopje','Gordana Siljanovska-Davkova',1991,25713,1800000);

INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Norway','NO','Europe','https://upload.wikimedia.org/wikipedia/commons/d/d9/Flag_of_Norway.svg','Oslo','Harald V',1905,385207,5500000);

INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Oman','OM','Asia','https://upload.wikimedia.org/wikipedia/commons/d/dd/Flag_of_Oman.svg','Muscat','Haitham bin Tariq',1650,309500,4600000);

INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Pakistan','PK','Asia','https://upload.wikimedia.org/wikipedia/commons/3/32/Flag_of_Pakistan.svg','Islamabad','Asif Ali Zardari',1947,881913,241000000);

INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Palau','PW','Oceania','https://upload.wikimedia.org/wikipedia/commons/4/48/Flag_of_Palau.svg','Ngerulmud','Surangel Whipps Jr.',1994,459,18000);

INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Panama','PA','North America','https://upload.wikimedia.org/wikipedia/commons/a/ab/Flag_of_Panama.svg','Panama City','José Raúl Mulino',1903,75417,4500000);

INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Papua New Guinea','PG','Oceania','https://upload.wikimedia.org/wikipedia/commons/e/e3/Flag_of_Papua_New_Guinea.svg','Port Moresby','James Marape',1975,462840,10000000);

INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Paraguay','PY','South America','https://upload.wikimedia.org/wikipedia/commons/2/27/Flag_of_Paraguay.svg','Asunción','Santiago Peña',1811,406752,6800000);

INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Peru','PE','South America','https://upload.wikimedia.org/wikipedia/commons/c/cf/Flag_of_Peru.svg','Lima','Dina Boluarte',1821,1285216,34000000);

INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Philippines','PH','Asia','https://upload.wikimedia.org/wikipedia/commons/9/99/Flag_of_the_Philippines.svg','Manila','Ferdinand Marcos Jr.',1898,300000,114000000);

INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Poland','PL','Europe','https://upload.wikimedia.org/wikipedia/en/1/12/Flag_of_Poland.svg','Warsaw','Andrzej Duda',1918,312696,38000000);

INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Portugal','PT','Europe','https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_Portugal.svg','Lisbon','Marcelo Rebelo de Sousa',1143,92212,10300000);

INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Qatar','QA','Asia','https://upload.wikimedia.org/wikipedia/commons/6/65/Flag_of_Qatar.svg','Doha','Tamim bin Hamad Al Thani',1971,11586,2900000);

INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Romania','RO','Europe','https://upload.wikimedia.org/wikipedia/commons/7/73/Flag_of_Romania.svg','Bucharest','Klaus Iohannis',1877,238397,19000000);

INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Russia','RU','Europe','https://upload.wikimedia.org/wikipedia/en/f/f3/Flag_of_Russia.svg','Moscow','Vladimir Putin',1991,17098246,146000000);

INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Rwanda','RW','Africa','https://upload.wikimedia.org/wikipedia/commons/1/17/Flag_of_Rwanda.svg','Kigali','Paul Kagame',1962,26338,14000000);

INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Saint Kitts and Nevis','KN','North America','https://upload.wikimedia.org/wikipedia/commons/f/fe/Flag_of_Saint_Kitts_and_Nevis.svg','Basseterre','Terrance Drew',1983,261,47000);

INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Saint Lucia','LC','North America','https://upload.wikimedia.org/wikipedia/commons/9/9f/Flag_of_Saint_Lucia.svg','Castries','Philip J. Pierre',1979,617,180000);

INSERT INTO country (country_name, country_abbreviation, country_continent, country_flag, country_capital, country_leader, country_independence_year, country_area, country_population) VALUES ('Saint Vincent and the Grenadines','VC','North America','https://upload.wikimedia.org/wikipedia/commons/6/6d/Flag_of_Saint_Vincent_and_the_Grenadines.svg','Kingstown','Ralph Gonsalves',1979,389,110000);

SELECT *
FROM country
;